version: "1.0"
info:
  model: int-scaffold
packages:
- name: Adap7MarchProject
  gitServerName: Adapter
  gitUrl: https://github.com/Sephali-Smrutisikha-IBM-1
  gitUsername: Sephali-Smrutisikha-IBM-1
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_Adapter
  packages:
  - name: Adap7MarchProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.networkProtocol
  : ""
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.trustStore
  : ""
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.portNumber
  : "1521"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.user
  : JDBC_BVT
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionEnabled
  : "false"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.dbType
  : ORACLE
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.databaseName
  : ORCL
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.keyStore
  : ""
  ? artConnection.Adap7MarchProject.project.adap7march.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Adapter.connectionSettings.otherProperties
  : ""
