version: "1.0"
info:
  model: int-scaffold
packages:
- name: Adap7MarchProject
  gitServerName: Adapter
  gitUrl: https://github.com/Sephali-Smrutisikha-IBM-1
  gitUsername: Sephali-Smrutisikha-IBM-1
  gitBranch: main
